db:
  port: "5432"
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
server:
  host: "localhost"
  port: ":8080"
redis:
  host: "localhost"
  port: "6379"
  password: ""


 

